

<NotesScreen>:
    id:ntsscreen
    orientation: "vertical"
    canvas.before:
        Color:
            rgba: (1, 1, 1, 1)
        Rectangle:
            size: self.size
            pos: self.pos
    BackBox:
        bcolor: app.color_bg_cream
        size_hint_y: .1
        padding:[10,0,10,0]
        MDIconButton:
            icon: "chevron-double-left"
            size_hint_x: .1
            pos_hint:{"center_x": .5, "center_y": .5}
            on_release: app.nav_bck()
        MDLabel:
            text:"NOTES"
            size_hint_x: .4
            halign: "center"
            pos_hint:{"center_x": .5, "center_y": .5}
        BackBox:
            id: searchb
            size_hint_x: .4
            padding: 2
        MDIconButton:
            id: sh
            icon:"text-box-search-outline" 
            on_press: self.icon = "text-box-remove-outline" if self.icon == "text-box-search-outline"  else "text-box-search-outline" ; root.add() 
            size_hint_x: .08
            halign: "center"
            pos_hint:{"center_x": .5, "center_y": .5}
    BackBox:
        size_hint_y: .1
        padding: [100, 0 ,10, 0]
        BackBox:
            orientation: "horizontal"
            size_hint_y: None
            height: dp(42)
            bcolor: app.color_bg_grey
            spacing: dp(12)
            padding: dp(12)
            radius: [10]
            pos_hint: {"center_x": .5, "center_y": .5}
            Text:
                text:"NAME"
                color: app.color_text_light
                font_size: app.fonts.size.h3
                size_hint_x: .2
            Text:
                text:"SIZE"
                color: app.color_text_light
                font_size: app.fonts.size.h3
                size_hint_x: .2
            Text:
                text:"DATE"
                color: app.color_text_light
                font_size: app.fonts.size.h3
                size_hint_x: .2
            Text:
                text:"DOWNLOADS"
                color: app.color_text_light
                font_size: app.fonts.size.h3
                size_hint_x: .2
            Text:
                text:"RATINGS"
                color: app.color_text_light
                font_size: app.fonts.size.h3
                size_hint_x: .2
    BackBox: 
        size_hint_y: .82
        padding:[10,0,10,0]
        ScrollView:
            do_scroll: [False, True] 
            size_hint_y: None
            height: self.parent.height
            GridLayout:
                id: gl_notes
                cols: 1
                spacing: dp(8)
                padding: [0, 20,0,0]
                size_hint_y: None
                height: self.minimum_height

<NotesTile>:
    id: tile_scrn
    size_hint_y: None
    height: dp(42)
    padding: [0,5,0,5]
    canvas.before:
        Color:
            rgba: app.color_light_blue
        Rectangle:
            pos: self.pos
            size: [self.size[0], dp(1)]
    Image:
        source:".venv/assets/imgs/pdf.png"
        size_hint_x:None
        width: dp(100)
        size_hint_y: None
        height: dp(60)
    Text:
        text:"Example.pdf"
        color: app.color_text_light
        font_size: app.fonts.size.h3
        size_hint_x: .2
    Text:
        text:"13MB"
        color: app.color_text_light
        font_size: app.fonts.size.h3
        size_hint_x: .2
    Text:
        text:"20/01/2025"
        color: app.color_text_light
        font_size: app.fonts.size.h3
        size_hint_x: .2
    BackBox:
        size_hint_x: .2
          
        MDIconButton:
            icon: "arrow-collapse-down"
            pos_hint:{"center_x": .5, "center_y": .5}
        MDLabel:
            text:"200k"
            color: app.color_text_light
            font_size: app.fonts.size.h3 
            pos_hint:{"center_x": .5, "center_y": .5}

    BackBox:
        size_hint_x: .2
        BackBox:
            pos_hint:{"center_x": .5, "center_y": .5}
            MDIconButton:    
                id: star1
                icon: "star-outline"
                theme_icon_color: "Custom"
                on_release: root.rate_star1()
            MDIconButton:
                id: star2
                icon: "star-outline"
                theme_icon_color: "Custom"
                on_release: root.rate_star2()
            MDIconButton:
                id: star3
                icon: "star-outline"
                theme_icon_color: "Custom"
                on_release: root.rate_star3()
            MDIconButton:
                id: star4
                icon: "star-outline"
                theme_icon_color: "Custom"
                on_release: root.rate_star4()
            MDIconButton:
                id: star5
                icon: "star-outline"
                theme_icon_color: "Custom"
                on_release: root.rate_star5()
 